name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NIXPKGS_REF: "nixpkgs/nixpkgs-unstable"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Install direnv
        run: nix profile install --impure --inputs-from . nixpkgs#direnv nixpkgs#nix-direnv

      - name: Enable direnv
        run: |
          echo "use flake" >> .envrc
          direnv allow

      - name: Run jobs
        run: direnv exec . engage

  artifacts:
      needs: ci
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/setup

        - name: Build artifacts
          run: nix build

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          with:
            name: artifacts
            path: result/bin/**

